### PR TITLE
1.10.0

### PR DESCRIPTION
**Pull request by andrew-gresyk**

### CODE REVIEW

**Comment by fire** [comment]
Do you need help switching to github actions?

**Comment by andrew-gresyk** [comment]
I kinda need help setting up all the compilers locally on a windows machine :)
How would you do this build matrix in github actions?

**Comment by fire** [comment]
This is unrelated but if you want llvm-mingw to cross compile from any of the platforms. There is also pdb generation.

https://github.com/mstorsjo/llvm-mingw

From my point of view, you can directly spin mac, linux and windows build natively on github actions.

**Comment by fire** [comment]
See how I did some of these for my tfd and godot engine build here https://github.com/V-Sekai/godot-tfd/tree/main/.github/workflows to support mac, linux and windows.

**Comment by andrew-gresyk** [comment]
If you have a look at https://github.com/andrew-gresyk/HFSM2/blob/master/.travis.yml
I never want to touch it, let alone recreate in anything else :D

**Comment by fire** [comment]
Sure. It probably isn't as complicated as porting Godot Engine from scons to bazel, cmake and meson. :D

**Comment by andrew-gresyk** [comment]
Sounds painful!

**Pull request merged**
